name: ExpressJs CICD PileLines

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["*"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node Js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci
      - name: testing
        run: npm test
